data<-read.delim("household_power_consumption.txt",sep=";")
data$Date<-as.Date(as.character(data$Date),"%d/%m/%Y")
data<-data[data$Date>='2007-02-01'& data$Date<='2007-02-02',]
data$DateTime<-strptime(paste(data$Date,as.character(data$Time)),format="%Y-%m-%d %H:%M:%S")
data$Global_active_power<-as.numeric(as.character(data$Global_active_power))
data$Sub_metering_1<-as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2<-as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3<-as.numeric(as.character(data$Sub_metering_3))
data$Voltage<-as.numeric(as.character(data$Voltage))
data$Global_reactive_power<-as.numeric(as.character(data$Global_reactive_power))
png(file="plot4.png",width=480, height=480)
par(mfrow = c(2, 2))
with(data,plot(DateTime,Global_active_power,type="l",ylab="Global Active Power",xlab=""))
with(data,plot(DateTime,Voltage,type="l",xlab="datetime"))
with(data,plot(DateTime,Sub_metering_1,type="l",ylab="Energy sub metering",xlab=""))
with(data,lines(DateTime,Sub_metering_2,col="red"))
with(data,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright", col= c("black","red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),bty = "n")
with(data,plot(DateTime,Global_reactive_power,type="l",xlab="datetime"))
dev.off()
