data<-read.delim("household_power_consumption.txt",sep=";")
data$Date<-as.Date(as.character(data$Date),"%d/%m/%Y")
data<-data[data$Date>='2007-02-01'& data$Date<='2007-02-02',]
data$DateTime<-strptime(paste(data$Date,as.character(data$Time)),format="%Y-%m-%d %H:%M:%S")
data$Global_active_power<-as.numeric(as.character(data$Global_active_power))
data$Sub_metering_1<-as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2<-as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3<-as.numeric(as.character(data$Sub_metering_3))
#par(pin=c(6,5))
png(file="plot3.png",width=480, height=480)
with(data,plot(DateTime,Sub_metering_1,type="l",ylab="Energy sub metering",xlab=""))
with(data,lines(DateTime,Sub_metering_2,col="red"))
with(data,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright", col= c("black","red","blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),lty=c(1,1,1))
dev.off()
